// List of possible vibes
const vibes = [
    "Crashing Out",
    "I Want to Go Home",
    "Need Coffee ASAP",
    "Just Woke Up",
    "Still in Bed",
    "Can't Even",
    "Too Tired for This",
    "Why Am I Awake",
    "Need a Nap",
    "Brain Not Working",
    "Just Vibing",
    "Chilling Hard",
    "Feeling Groovy",
    "Vibing Hard",
    "Peaceful Energy",
    "Good Vibes",
    "Vibing to the Max",
    "Chillax Mode",
    "Positive Vibes",
    "Vibing with the Universe",
    "Zen Vibes",
    "Vibing on Cloud Nine",
    "Good Energy",
    "Vibing with the Flow",
    "Chill and Relaxed",
    "Vibing with Style",
    "Not Today",
    "Maybe Tomorrow",
    "Can't Deal",
    "Over It",
    "Done with Everything",
    "Need a Break",
    "Too Much Going On",
    "Brain is Fried",
    "Need a Vacation",
    "Counting Down to Weekend",
    "Monday Blues",
    "TGIF Mode",
    "Weekend Mode",
    "Holiday Mode",
    "Vacation Brain",
    "Beach Mode",
    "Mountain Mode",
    "City Mode",
    "Night Owl Mode",
    "Early Bird Mode",
    "Coffee Addict",
    "Tea Time",
    "Music in My Head",
    "Dance Mode",
    "Art Mode",
    "Creative Mode",
    "Study Mode",
    "Work Mode",
    "Weekend Vibes",
    "Vacation Vibes",
    "Adventure Mode",
    "Explorer Mode",
    "Dream Mode",
    "Fantasy Mode",
    "Magical Mode",
    "Mystical Mode",
    "Spiritual Mode",
    "Meditation Mode",
    "Yoga Mode",
    "Fitness Mode",
    "Gaming Mode",
    "Movie Mode",
    "Book Mode",
    "Poetry Mode",
    "Nature Mode",
    "Ocean Mode",
    "Desert Mode",
    "Arctic Mode",
    "Tropical Mode",
    "Urban Mode",
    "Rural Mode",
    "Space Mode",
    "Galaxy Mode",
    "Stellar Mode",
    "Lunar Mode",
    "Solar Mode",
    "Cosmic Mode",
    "Earth Mode",
    "Fire Mode",
    "Water Mode",
    "Air Mode",
    "Earth Mode",
    "Crystal Mode",
    "Gemstone Mode",
    "Mineral Mode",
    "Botanical Mode",
    "Floral Mode",
    "Garden Mode",
    "Spring Mode",
    "Summer Mode",
    "Autumn Mode",
    "Winter Mode",
    "Festive Mode",
    "Holiday Mode",
    "Celebration Mode",
    "Party Mode",
    "Social Mode",
    "Friendly Mode",
    "Love Mode",
    "Romantic Mode",
    "Passionate Mode",
    "Creative Flow",
    "Artistic Flow",
    "Musical Flow",
    "Dance Flow",
    "Poetic Flow",
    "Literary Flow",
    "Cinematic Flow",
    "Theatrical Flow",
    "Dramatic Flow",
    "Comedic Flow",
    "Humorous Flow",
    "Witty Flow",
    "Clever Flow",
    "Intellectual Flow",
    "Academic Flow",
    "Scientific Flow",
    "Mathematical Flow",
    "Logical Flow",
    "Analytical Flow",
    "Philosophical Flow",
    "Theoretical Flow",
    "Practical Flow",
    "Technical Flow",
    "Digital Flow",
    "Virtual Flow",
    "Cyber Flow",
    "Tech Flow",
    "Innovative Flow",
    "Inventive Flow",
    "Creative Flow",
    "Imaginative Flow",
    "Fantastical Flow",
    "Magical Flow",
    "Mystical Flow",
    "Spiritual Flow",
    "Ethereal Flow",
    "Celestial Flow",
    "Astral Flow",
    "Cosmic Flow",
    "Universal Flow",
    "Infinite Flow",
    "Eternal Flow",
    "Timeless Flow",
    "Ageless Flow",
    "Boundless Flow",
    "Limitless Flow",
    "Endless Flow",
    "Need More Coffee",
    "Too Much Coffee",
    "Running on Empty",
    "Barely Functioning",
    "Just Surviving",
    "Hanging in There",
    "Making It Work",
    "Faking It Till I Make It",
    "Pretending to Adult",
    "Adulting is Hard",
    "Why Am I Like This",
    "What Even Is Time",
    "Lost in Thoughts",
    "Brain on Autopilot",
    "Auto-Pilot Mode",
    "Zombie Mode",
    "Sleepwalking",
    "Daydreaming",
    "Mind Wandering",
    "Lost in Space",
    "Floating Through Life",
    "Drifting Away",
    "Fading Fast",
    "Need a Reset",
    "System Overload",
    "Brain.exe Has Stopped",
    "404 Brain Not Found",
    "Blue Screen of Life",
    "Need to Reboot",
    "Loading...",
    "Buffering...",
    "Processing...",
    "Calculating...",
    "Thinking...",
    "Still Thinking...",
    "Overthinking...",
    "Analysis Paralysis",
    "Decision Fatigue",
    "Choice Overload",
    "Too Many Options",
    "Can't Decide",
    "Indecisive Mode",
    "Maybe Later",
    "Procrastination Mode",
    "Last Minute Mode",
    "Deadline Mode",
    "Panic Mode",
    "Stress Mode",
    "Anxiety Mode",
    "Calm Mode",
    "Chill Mode",
    "Relaxed Mode",
    "Peace Mode",
    "Tranquil Mode",
    "Serene Mode",
    "Bliss Mode",
    "Joy Mode",
    "Happy Mode",
    "Content Mode",
    "Satisfied Mode",
    "Grateful Mode",
    "Blessed Mode",
    "Thankful Mode",
    "Appreciative Mode",
    "Mindful Mode",
    "Present Mode",
    "Here and Now",
    "Living in the Moment",
    "Seizing the Day",
    "Carpe Diem Mode",
    "YOLO Mode",
    "Living Life",
    "Enjoying Life",
    "Loving Life",
    "Life is Good",
    "Life is Beautiful",
    "Life is Amazing",
    "Life is Wonderful",
    "Life is Perfect",
    "Life is Great",
    "Life is Awesome",
    "Life is Fantastic",
    "Life is Incredible",
    "Life is Magical",
    "Life is Mystical",
    "Life is Spiritual",
    "Life is Ethereal",
    "Life is Celestial",
    "Life is Cosmic",
    "Life is Universal",
    "Life is Infinite",
    "Life is Eternal",
    "Life is Timeless",
    "Life is Ageless",
    "Life is Boundless",
    "Life is Limitless",
    "Life is Endless"
];

// Get DOM elements
const vibeElement = document.getElementById('vibe');
const checkButton = document.getElementById('checkButton');

// Function to get random vibe
function getRandomVibe() {
    const randomIndex = Math.floor(Math.random() * vibes.length);
    return vibes[randomIndex];
}

// Function to update vibe with animation
function updateVibe() {
    vibeElement.classList.remove('changed');
    void vibeElement.offsetWidth; // Trigger reflow
    vibeElement.classList.add('changed');
    vibeElement.textContent = getRandomVibe();
}

// Add click event listener to button
checkButton.addEventListener('click', updateVibe);

// Initialize particles
particlesJS('particles-js', {
    particles: {
        number: {
            value: 80,
            density: {
                enable: true,
                value_area: 800
            }
        },
        color: {
            value: '#ffffff'
        },
        shape: {
            type: 'circle'
        },
        opacity: {
            value: 0.5,
            random: false,
            anim: {
                enable: false
            }
        },
        size: {
            value: 3,
            random: true
        },
        line_linked: {
            enable: true,
            distance: 150,
            color: '#ffffff',
            opacity: 0.4,
            width: 1
        },
        move: {
            enable: true,
            speed: 2,
            direction: 'none',
            random: false,
            straight: false,
            out_mode: 'out',
            bounce: false
        }
    },
    interactivity: {
        detect_on: 'canvas',
        events: {
            onhover: {
                enable: true,
                mode: 'grab'
            },
            onclick: {
                enable: true,
                mode: 'push'
            },
            resize: true
        },
        modes: {
            grab: {
                distance: 140,
                line_linked: {
                    opacity: 1
                }
            },
            push: {
                particles_nb: 4
            }
        }
    },
    retina_detect: true
}); 